sonarr:
  image: linuxserver/sonarr
  links:
    - transmission:transmission
  ports:
    - 8989:8989
  volumes:
    # In order to the container uses the same date which is in the host, it is necessary to share /etc/localtime file
    - /etc/localtime:/etc/localtime:ro
    - /dev/rtc:/dev/rtc:ro
    - ./config:/config:rw
    - ./tvshows:/tv:rw

  environment:
    # The PGID and PUID values set the user / group you'd like your container to 'run as' to the host OS. This can be a user you've created or even root (not recommended).
    - PUID=root 
    - PGID=root

transmission:
  image: dperson/transmission
  ports:
    - 9091:9091
  volumes:
    # In order to the container uses the same date which is in the host, it is necessary to share /etc/localtime file
    - /etc/localtime:/etc/localtime:ro
    - ./tvshows:/var/lib/transmission-daemon/downloads:rw
